# Generated by Django 4.2.6 on 2023-10-28 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DroneCustomer.cart')),
            ],
        ),
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='small', max_length=10)),
                ('drone_weight_g', models.PositiveIntegerField()),
                ('battery_capacity_mAh', models.PositiveIntegerField()),
                ('battery_voltage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('battery_level', models.DecimalField(decimal_places=1, max_digits=2)),
                ('enabled', models.BooleanField(default=True)),
                ('in_flight', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OptionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField()),
                ('status', models.CharField(default='Pending', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DroneCustomer.drone')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MenuOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('display_type', models.CharField(choices=[('checkbox', 'Checkbox'), ('radio', 'Radio')], max_length=10)),
                ('min_amount', models.PositiveIntegerField(default=0)),
                ('max_amount', models.PositiveIntegerField(default=1)),
                ('values', models.ManyToManyField(related_name='menu_option', to='DroneCustomer.optionvalue')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('enabled', models.BooleanField(default=True)),
                ('qty', models.IntegerField(default=0)),
                ('options', models.ManyToManyField(related_name='menu_items', to='DroneCustomer.menuoption')),
            ],
        ),
        migrations.CreateModel(
            name='DroneOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drones', models.ManyToManyField(related_name='owner', to='DroneCustomer.drone')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='drone_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('menu_items', models.ManyToManyField(related_name='categories', to='DroneCustomer.menuitem')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DroneCustomer.category')),
            ],
        ),
        migrations.CreateModel(
            name='CartItemOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DroneCustomer.cartitem')),
                ('option_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DroneCustomer.optionvalue')),
            ],
        ),
        migrations.AddField(
            model_name='cartitem',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DroneCustomer.menuitem'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='options',
            field=models.ManyToManyField(through='DroneCustomer.CartItemOption', to='DroneCustomer.optionvalue'),
        ),
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(through='DroneCustomer.CartItem', to='DroneCustomer.menuitem'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL),
        ),
    ]
