# Generated by Django 4.2.6 on 2023-11-05 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DroneCustomer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
