# Generated by Django 4.2.6 on 2023-10-30 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DroneCustomer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cone',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
