# Generated by Django 4.2.6 on 2023-11-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DroneCustomer', '0002_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
