# Generated by Django 4.2.7 on 2023-11-18 19:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DroneCustomer', '0004_remove_order_delivered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='dollar_revenue',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AddField(
            model_name='drone',
            name='hours_worked',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4),
        ),
    ]
