# Generated by Django 4.2.7 on 2023-11-19 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DroneCustomer', '0005_drone_dollar_revenue_drone_hours_worked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drone',
            name='hours_worked',
        ),
        migrations.AddField(
            model_name='drone',
            name='minutes_worked',
            field=models.IntegerField(default=0),
        ),
    ]
